config/routes.rb
Rails.application.routes.draw do
  resources :facts
  resources :quotations
  get '/quotations/projects/index(.:format)' => 'quotations#project_index'
  get '/quotations/projects/show/:project_name(.:format)' => 'quotations#show_projects'

  get '/cost_comparisons/:project_name(.:format)' => 'cost_comparisons#show'
  get '/cost_comparisons/download/:project_name(.:format)' => 'cost_comparisons#download'

  resources :users

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  belongs_to :user
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?
  
  protected
  
  def json_request?
    request.format.json?
  end
end

app/controllers/cost_comparisons_controller.rb
class CostComparisonsController < ApplicationController

  def show
    #@quotations = Quotation.where('project_name = ?', cost_comparison_params[:project_name])
    #@facts = Fact.where('project_name = ?', cost_comparison_params[:project_name])
    @quotations = Quotation.where('project_name = ?', params[:project_name])
    @facts = Fact.where('project_name = ?', params[:project_name])
  end

  def download
    @quotations = Quotation.where('project_name = ?', params[:project_name]).order('updated_at')
    @facts = Fact.where('project_name = ?', params[:project_name]).order('updated_at')

    respond_to do |format|
      format.html { redirect_to :action => 'download', :format => 'csv' } # .csv がなくアクセスした場合はリダイレクト
      #format.csv { render :content_type => 'text/csv' }
      format.csv { send_data render_to_string, filename: "cost-comparisons-#{Time.now.to_date.to_s}.csv", type: :csv }
    end
  end

  private

    # Web APIのみで、チェック不要のため使用しない
    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_comparison_params
      #params.permit(:project_name)
    end

end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: [:show, :edit, :update, :destroy]

  # GET /facts
  # GET /facts.json
  def index
    @facts = Fact.all
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(fact_params)

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1
  # PATCH/PUT /facts/1.json
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to facts_url, notice: 'Fact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_params
      params.require(:fact).permit(:user_id, :project_name, :fact_text, :man_day)
    end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  #protect_from_forgery :except => [:create, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  def project_index
    @quotations_projects = Quotation.group("project_name").select("project_name")
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:user_id, :project_name, :quotation_text, :man_day)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cost_comparisons_helper.rb
module CostComparisonsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/facts/_form.html.erb
<%= form_for(@fact) do |f| %>
  <% if @fact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
      <% @fact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_name %><br>
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :fact_text %><br>
    <%= f.text_field :fact_text %>
  </div>
  <div class="field">
    <%= f.label :man_day %><br>
    <%= f.text_field :man_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing Fact</h1>

<%= render 'form' %>

<%= link_to 'Show', @fact %> |
<%= link_to 'Back', facts_path %>

app/views/facts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Facts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project name</th>
      <th>Fact text</th>
      <th>Man-day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facts.each do |fact| %>
      <tr>
        <td><%= fact.user %></td>
        <td><%= fact.project_name %></td>
        <td><%= fact.fact_text %></td>
        <td><%= fact.man_day %></td>
        <td><%= link_to 'Show', fact %></td>
        <td><%= link_to 'Edit', edit_fact_path(fact) %></td>
        <td><%= link_to 'Destroy', fact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fact', new_fact_path %>

app/views/facts/new.html.erb
<h1>New Fact</h1>

<%= render 'form' %>

<%= link_to 'Back', facts_path %>

app/views/facts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @fact.user %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @fact.project_name %>
</p>

<p>
  <strong>Fact text:</strong>
  <%= @fact.fact_text %>
</p>

<p>
  <strong>Man-day:</strong>
  <%= @fact.man_day %>
</p>

<%= link_to 'Edit', edit_fact_path(@fact) %> |
<%= link_to 'Back', facts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiffCost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotations/_form.html.erb
<%= form_for(@quotation) do |f| %>
  <% if @quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% @quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_name %><br>
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :quotation_text %><br>
    <%= f.text_field :quotation_text %>
  </div>
  <div class="field">
    <%= f.label :man_day %><br>
    <%= f.text_field :man_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotations/edit.html.erb
<h1>Editing Quotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project name</th>
      <th>Quotation text</th>
      <th>Man-day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.user %></td>
        <td><%= quotation.project_name %></td>
        <td><%= quotation.quotation_text %></td>
        <td><%= quotation.man_day %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form' %>

<%= link_to 'Back', quotations_path %>

app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @quotation.user %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @quotation.project_name %>
</p>

<p>
  <strong>Quotation text:</strong>
  <%= @quotation.quotation_text %>
</p>

<p>
  <strong>Man-day:</strong>
  <%= @quotation.man_day %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_id %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>